//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeWork
    {
        public int HID { get; set; }
        public string TitleLesson { get; set; }
        public string Subject { get; set; }
        public string TeacherName { get; set; }
        public string TeacherID { get; set; }
        public string DeliveryDate { get; set; }
    }
}
