//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int SID { get; set; }
        public int RoleID { get; set; }
        public string Name { get; set; }
        public string Fname { get; set; }
        public string CodeMeli { get; set; }
        public string Reshte { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ActiveCode { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
